version: '3'
services:
  gradle-project-analyzer:
    image: ghcr.io/windsekirun/gradle-project-analyzer
    container_name: gradle-project-analyzer 
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=file:/app/data/gradle-project-analyzer.db
      - AUTH_TOKEN=sample
    volumes:
      - gpa-data:/app/data
    restart: unless-stopped
  
volumes:
  gpa-data: