name: Build, Push Docker Image, and Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set repository name to lowercase
        id: set-repo-name
        run: echo "REPO_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME_LOWER }}:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Get previous tag
        id: prev-tag
        run: |
          git fetch --tags
          TAGS=($(git tag -l --sort=-creatordate))
          if [ ${#TAGS[@]} -gt 1 ]; then
            PREV_TAG=${TAGS[1]}
          else
            PREV_TAG=''
          fi
          echo "PREVIOUS_TAG=${PREV_TAG}" >> $GITHUB_ENV

      - name: Set release body
        id: set-body
        run: |
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "RELEASE_BODY=Docker image for \`${GITHUB_REF_NAME}\` has been built and pushed to ghcr.io." >> $GITHUB_ENV
          else
            COMPARE_URL="https://github.com/${GITHUB_REPOSITORY}/compare/${PREVIOUS_TAG}...${GITHUB_REF_NAME}"
            echo "RELEASE_BODY=Docker image for \`${GITHUB_REF_NAME}\` has been built and pushed to ghcr.io.\n\n[Commits](${COMPARE_URL})" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
